# File Name: xinitrc
# File Path: /etc/X11/xinit/xinitrc
# Description: System-wide xinitrc configuration file.

# Copyright (c) 2024 Aryan
# SPDX-Licence-Identifier: BSD-3-Clause

# Version: 1.0.1

exec dbus-launch --exit-with-session i3
