# File Name: xinitrc
# File Path: ${XDG_CONFIG_HOME}/X11/xinitrc
# Description: Xinitrc configuration file.

# Copyright (c) 2024 Aryan
# SPDX-Licence-Identifier: BSD-3-Clause

# Version: 1.0.0+delta

exec dbus-launch --exit-with-session i3
